In [3]:
import numpy as np  
a = np.arange(6)
a


array([0, 1, 2, 3, 4, 5])

In [1]:
import numpy as np  
a= np.arange(6).reshape((2,3))  
a


array([[0, 1, 2],
       [3, 4, 5]])

In [2]:
b=np.transpose(a)  
b 


array([[0, 3],
       [1, 4],
       [2, 5]])

In [4]:
a= np.array([[1, 2], [4, 5], [7, 8]])  
a


array([[1, 2],
       [4, 5],
       [7, 8]])

In [13]:
b=np.transpose(a, (1,0))  
b 


array([[1, 4, 7],
       [2, 5, 8]])

In [6]:
b=np.transpose(a) 
b


array([[1, 4, 7],
       [2, 5, 8]])

In [17]:
a=np.ones((12,32,123,64))  
a


array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        ...,

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
    

In [18]:
b=np.transpose(a,(1,3,0,2)).shape  
b  


(32, 64, 12, 123)

In [19]:
c=np.transpose(a,(0,3,1,2)).shape  
c


(12, 64, 32, 123)